version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: task_db
    environment:
      POSTGRES_USER: kvervandi
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
